# Generated by Django 3.0.8 on 2020-07-12 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applicationblocks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.AddField(
            model_name='reference',
            name='author',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='applicationblocks.Author'),
            preserve_default=False,
        ),
    ]
