# Generated by Django 3.0.8 on 2020-07-12 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicationblocks', '0002_auto_20200712_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='reference',
            name='coauthors',
            field=models.ManyToManyField(related_name='coauthor_id', to='applicationblocks.Author'),
        ),
    ]
