# Generated by Django 3.0.8 on 2020-07-12 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicationblocks', '0003_reference_coauthors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='coauthors',
            field=models.ManyToManyField(related_name='coauthor_id', related_query_name='coauthor_id', to='applicationblocks.Author'),
        ),
    ]
