# Generated by Django 3.0.8 on 2020-07-21 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicationblocks', '0004_auto_20200712_2006'),
    ]

    operations = [
        migrations.CreateModel(
            name='Editor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=40)),
                ('last_name', models.CharField(default='', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='author',
            name='name',
        ),
        migrations.RemoveField(
            model_name='reference',
            name='coauthors',
        ),
        migrations.RemoveField(
            model_name='reference',
            name='someNumber',
        ),
        migrations.RemoveField(
            model_name='reference',
            name='title',
        ),
        migrations.AddField(
            model_name='author',
            name='first_name',
            field=models.CharField(default='firstname', max_length=40),
        ),
        migrations.AddField(
            model_name='author',
            name='last_name',
            field=models.CharField(default='lastname', max_length=40),
        ),
        migrations.AddField(
            model_name='reference',
            name='book_title',
            field=models.CharField(default='title', max_length=80),
        ),
        migrations.AddField(
            model_name='reference',
            name='isbn',
            field=models.CharField(default='isbn', max_length=40, unique=True),
        ),
        migrations.AddField(
            model_name='reference',
            name='journal',
            field=models.CharField(default='journal', max_length=40),
        ),
        migrations.AddField(
            model_name='reference',
            name='month',
            field=models.CharField(default='month', max_length=12),
        ),
        migrations.AddField(
            model_name='reference',
            name='publisher',
            field=models.CharField(default='publisher', max_length=40),
        ),
        migrations.AddField(
            model_name='reference',
            name='volume',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='reference',
            name='year',
            field=models.IntegerField(default=2020),
        ),
        migrations.RemoveField(
            model_name='reference',
            name='author',
        ),
        migrations.AddField(
            model_name='reference',
            name='author',
            field=models.ManyToManyField(related_name='author_id', related_query_name='author_id', to='applicationblocks.Author'),
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ManyToManyField(to='applicationblocks.Author')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40, unique=True)),
                ('team', models.ManyToManyField(to='applicationblocks.Team')),
            ],
        ),
        migrations.AddField(
            model_name='reference',
            name='editor',
            field=models.ManyToManyField(related_name='editor_id', related_query_name='editor_id', to='applicationblocks.Editor'),
        ),
    ]
