# Generated by Django 3.0.8 on 2020-08-27 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicationblocks', '0006_auto_20200827_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='name',
            field=models.CharField(default='', max_length=50, unique=True),
        ),
    ]
