# Generated by Django 3.0.8 on 2020-08-28 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applicationblocks', '0007_team_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reference',
            old_name='uploadedBy',
            new_name='authors',
        ),
        migrations.AddField(
            model_name='reference',
            name='team',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='team_id', related_query_name='team_id', to='applicationblocks.Team'),
        ),
    ]
