# Generated by Django 3.0.8 on 2020-08-28 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicationblocks', '0008_auto_20200828_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='reference',
            name='doi',
            field=models.CharField(default='doi', max_length=40, unique=True),
        ),
        migrations.AddField(
            model_name='reference',
            name='issn',
            field=models.CharField(default='issn', max_length=40, unique=True),
        ),
    ]
