# Generated by Django 3.0.8 on 2020-08-29 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applicationblocks', '0010_project_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='reference',
            name='rank',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rank_id', related_query_name='rank_id', to='applicationblocks.Rank'),
        ),
        migrations.AlterField(
            model_name='reference',
            name='team',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_id', related_query_name='team_id', to='applicationblocks.Team'),
        ),
    ]
