# Generated by Django 3.0.8 on 2020-09-01 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applicationblocks', '0014_auto_20200901_1814'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reference',
            name='authors',
        ),
    ]
