# Generated by Django 3.0.8 on 2020-09-01 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicationblocks', '0016_reference_authors'),
    ]

    operations = [
        migrations.AddField(
            model_name='reference',
            name='address',
            field=models.CharField(default='address', max_length=100),
        ),
        migrations.AddField(
            model_name='reference',
            name='comment',
            field=models.CharField(default='comment', max_length=40),
        ),
        migrations.AddField(
            model_name='reference',
            name='eid',
            field=models.CharField(default='eid', max_length=40),
        ),
        migrations.AddField(
            model_name='reference',
            name='eprint',
            field=models.CharField(default='eprint', max_length=40),
        ),
        migrations.AddField(
            model_name='reference',
            name='file',
            field=models.CharField(default='file', max_length=240),
        ),
        migrations.AddField(
            model_name='reference',
            name='institution',
            field=models.CharField(default='institution', max_length=100),
        ),
        migrations.AddField(
            model_name='reference',
            name='keywords',
            field=models.CharField(default='keywords', max_length=340),
        ),
        migrations.AddField(
            model_name='reference',
            name='local_file',
            field=models.CharField(default='local_file', max_length=240),
        ),
        migrations.AddField(
            model_name='reference',
            name='location',
            field=models.CharField(default='location', max_length=60),
        ),
        migrations.AddField(
            model_name='reference',
            name='note',
            field=models.CharField(default='note', max_length=340),
        ),
        migrations.AddField(
            model_name='reference',
            name='number',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='reference',
            name='owner',
            field=models.CharField(default='owner', max_length=40),
        ),
        migrations.AddField(
            model_name='reference',
            name='pages',
            field=models.CharField(default='pages', max_length=40),
        ),
        migrations.AddField(
            model_name='reference',
            name='series',
            field=models.CharField(default='series', max_length=60),
        ),
        migrations.AddField(
            model_name='reference',
            name='url',
            field=models.CharField(default='url', max_length=240),
        ),
    ]
