# Generated by Django 3.0.8 on 2020-09-01 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicationblocks', '0017_auto_20200901_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editor',
            name='first_name',
            field=models.CharField(default='', max_length=90),
        ),
        migrations.AlterField(
            model_name='editor',
            name='last_name',
            field=models.CharField(default='', max_length=90),
        ),
        migrations.AlterField(
            model_name='project',
            name='code',
            field=models.CharField(max_length=90, unique=True),
        ),
        migrations.AlterField(
            model_name='rank',
            name='code',
            field=models.CharField(max_length=90, unique=True),
        ),
        migrations.AlterField(
            model_name='reference',
            name='comment',
            field=models.CharField(default='comment', max_length=90),
        ),
        migrations.AlterField(
            model_name='reference',
            name='doi',
            field=models.CharField(default='doi', max_length=90, unique=True),
        ),
        migrations.AlterField(
            model_name='reference',
            name='eid',
            field=models.CharField(default='eid', max_length=90),
        ),
        migrations.AlterField(
            model_name='reference',
            name='eprint',
            field=models.CharField(default='eprint', max_length=90),
        ),
        migrations.AlterField(
            model_name='reference',
            name='file',
            field=models.CharField(default='file', max_length=290),
        ),
        migrations.AlterField(
            model_name='reference',
            name='isbn',
            field=models.CharField(default='isbn', max_length=90, unique=True),
        ),
        migrations.AlterField(
            model_name='reference',
            name='issn',
            field=models.CharField(default='issn', max_length=90, unique=True),
        ),
        migrations.AlterField(
            model_name='reference',
            name='journal',
            field=models.CharField(default='journal', max_length=90),
        ),
        migrations.AlterField(
            model_name='reference',
            name='keywords',
            field=models.CharField(default='keywords', max_length=390),
        ),
        migrations.AlterField(
            model_name='reference',
            name='local_file',
            field=models.CharField(default='local_file', max_length=290),
        ),
        migrations.AlterField(
            model_name='reference',
            name='note',
            field=models.CharField(default='note', max_length=390),
        ),
        migrations.AlterField(
            model_name='reference',
            name='owner',
            field=models.CharField(default='owner', max_length=90),
        ),
        migrations.AlterField(
            model_name='reference',
            name='pages',
            field=models.CharField(default='pages', max_length=90),
        ),
        migrations.AlterField(
            model_name='reference',
            name='publisher',
            field=models.CharField(default='publisher', max_length=90),
        ),
        migrations.AlterField(
            model_name='reference',
            name='url',
            field=models.CharField(default='url', max_length=290),
        ),
    ]
