# Generated by Django 3.0.8 on 2020-09-01 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicationblocks', '0018_auto_20200901_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='doi',
            field=models.CharField(default='doi', max_length=90),
        ),
        migrations.AlterField(
            model_name='reference',
            name='isbn',
            field=models.CharField(default='isbn', max_length=90),
        ),
        migrations.AlterField(
            model_name='reference',
            name='issn',
            field=models.CharField(default='issn', max_length=90),
        ),
    ]
