# Generated by Django 3.0.8 on 2020-09-01 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicationblocks', '0019_auto_20200901_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='address',
            field=models.CharField(default='address', max_length=180),
        ),
        migrations.AlterField(
            model_name='reference',
            name='book_title',
            field=models.CharField(default='title', max_length=180),
        ),
        migrations.AlterField(
            model_name='reference',
            name='institution',
            field=models.CharField(default='institution', max_length=200),
        ),
        migrations.AlterField(
            model_name='reference',
            name='journal',
            field=models.CharField(default='journal', max_length=190),
        ),
        migrations.AlterField(
            model_name='reference',
            name='location',
            field=models.CharField(default='location', max_length=160),
        ),
        migrations.AlterField(
            model_name='reference',
            name='publisher',
            field=models.CharField(default='publisher', max_length=190),
        ),
        migrations.AlterField(
            model_name='reference',
            name='series',
            field=models.CharField(default='series', max_length=360),
        ),
    ]
