# Generated by Django 3.0.8 on 2020-09-01 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicationblocks', '0020_auto_20200901_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='volume',
            field=models.CharField(default='volume', max_length=20),
        ),
    ]
