# Generated by Django 3.0.8 on 2020-09-03 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicationblocks', '0021_auto_20200901_1937'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reference',
            old_name='authors',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='reference',
            old_name='book_title',
            new_name='title',
        ),
        migrations.AddField(
            model_name='reference',
            name='booktitle',
            field=models.CharField(default='booktitle', max_length=180),
        ),
        migrations.AddField(
            model_name='reference',
            name='key',
            field=models.CharField(default='key', max_length=20),
        ),
        migrations.AddField(
            model_name='reference',
            name='type',
            field=models.CharField(default='type', max_length=30),
        ),
    ]
