# Generated by Django 3.0.8 on 2020-09-07 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applicationblocks', '0022_auto_20200903_1115'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferenceAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default='key', max_length=200)),
                ('value', models.CharField(default='value', max_length=800)),
                ('reference', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reference_id', related_query_name='reference_id', to='applicationblocks.Reference')),
            ],
        ),
    ]
