# Generated by Django 3.0.8 on 2020-09-07 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicationblocks', '0023_referenceattribute'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referenceattribute',
            name='reference',
        ),
        migrations.AddField(
            model_name='reference',
            name='reference_attributes',
            field=models.ManyToManyField(default=None, related_name='editor_id', related_query_name='editor_id', to='applicationblocks.ReferenceAttribute'),
        ),
    ]
