# Generated by Django 3.0.8 on 2020-09-07 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applicationblocks', '0025_auto_20200907_1619'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reference',
            old_name='reference_attributes',
            new_name='attributes',
        ),
        migrations.RenameField(
            model_name='referenceattribute',
            old_name='key',
            new_name='name',
        ),
    ]
