# Generated by Django 3.0.8 on 2020-09-08 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicationblocks', '0026_auto_20200907_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(default='', max_length=350),
        ),
        migrations.AlterField(
            model_name='reference',
            name='doi',
            field=models.CharField(default='', max_length=90),
        ),
        migrations.AlterField(
            model_name='reference',
            name='isbn',
            field=models.CharField(default='', max_length=90),
        ),
        migrations.AlterField(
            model_name='reference',
            name='issn',
            field=models.CharField(default='', max_length=90),
        ),
        migrations.AlterField(
            model_name='reference',
            name='key',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='reference',
            name='title',
            field=models.CharField(default='', max_length=180),
        ),
        migrations.AlterField(
            model_name='reference',
            name='type',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='reference',
            name='year',
            field=models.IntegerField(default=0),
        ),
    ]
