# Generated by Django 3.0.8 on 2020-09-12 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applicationblocks', '0027_auto_20200908_1559'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Editor',
        ),
    ]
